### ISSUE TITLE
感謝加上真夏及問題回報

### ISSUE THREAD

**Issue by tatamu-fold** [janelin612/n46-crawler#3]
太感謝加上真夏了 本來以爲不會有了
另外飛鳥有時過長的標題會加載不到：https://janelin612.github.io/n46-crawler/mb/asuka.saito/?no=195

**Comment by janelin612** [comment]
我猜應該是標題有雙引號，跟HTML結構混在一起了，會再嘗試修正

**Comment by tatamu-fold** [comment]
@janelin612 謝謝！

**Comment by janelin612** [comment]
該問題已完成修正，包含乃木坂的爬蟲程式碼，並重爬了一次飛鳥的資料

**Comment by tatamu-fold** [comment]
感謝
